---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: true

- name: Install required software
  apt: name={{ item }} state=present
  become: true 
  with_items:
    - git
    - nginx
    - mysql-server
    - php7.0-fpm
    - php7.0-mysql
    - php7.0
    - python-mysqldb
    - fail2ban

- name: Configure fail2ban
  shell: cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local

- name: Install chrootkit
  apt: name=chrootkit state=present
