---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install required software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - git
    - nginx
    - mysql-server
    - php7.0-fpm
    - php7.0-mysql
    - php7.0
    - python-mysqldb
